### ISSUE TITLE
mbtools and rasbperry

### ISSUE THREAD

**Issue by JohannSim** [webstack/mbtools#3]
Hello,
I have an error when set up mbtools on rasbperry.

The two first steps works but when i input the order make, the function make returns:

make  all-recursive
make[1]: Entering directory '/home/pi/modbus/mbtools-master'
Making all in src
make[2]: Entering directory '/home/pi/modbus/mbtools-master/src'
  CC     option.o
option.c: In function ‘option_parse_mode’:
option.c:132:1: error: control reaches end of non-void function [-Werror=return-type]
cc1: all warnings being treated as errors
Makefile:334: recipe for target 'option.o' failed
make[2]: **\* [option.o] Error 1
make[2]: Leaving directory '/home/pi/modbus/mbtools-master/src'
Makefile:302: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/modbus/mbtools-master'
Makefile:242: recipe for target 'all' failed
make: **\* [all] Error 2

I have no ideas how to fix the problem, can you help me?

Thank you for your help

Johann

**Comment by stephane** [comment]
Yes it's a missing return, I'll fix it.
